using Backend.Data;
using Backend.Exceptions;
using Backend.Models;
using Backend.Repositories.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace Backend.Repositories
{
    // ════════════════════════════════════════════════════════════════════════
    // LAYER 1: USER REPOSITORY (Implementation)
    // ════════════════════════════════════════════════════════════════════════
    // This class does the ACTUAL database work using Entity Framework Core.
    // EF Core converts your C# code into Oracle SQL automatically.
    //
    // C# Code               →   Oracle SQL generated by EF Core
    // ─────────────────────────────────────────────────────────
    // GetByEmailAsync()     →   SELECT * FROM USERS WHERE EMAIL = :email
    // AddAsync()            →   INSERT INTO USERS (...) VALUES (...)
    // UpdateAsync()         →   UPDATE USERS SET ... WHERE ID = :id
    //
    // The Service layer calls this — it never talks to the DB directly.
    // ════════════════════════════════════════════════════════════════════════

    public class UserRepository : IUserRepository
    {
        // AppDbContext is the EF Core bridge to Oracle
        private readonly AppDbContext _context;

        // Constructor Injection: .NET gives us the DbContext automatically
        public UserRepository(AppDbContext context)
        {
            _context = context;
        }

        // ── GET BY ID ────────────────────────────────────────────────────
        public async Task<User?> GetByIdAsync(int id)
        {
            // EF Core SQL: SELECT * FROM USERS WHERE ID = :id
            // Returns null if not found (that's what ? means on User?)
            return await _context.Users
                .FirstOrDefaultAsync(u => u.Id == id);
        }

        // ── GET BY EMAIL ─────────────────────────────────────────────────
        public async Task<User?> GetByEmailAsync(string email)
        {
            // Case-insensitive email search
            // EF Core SQL: SELECT * FROM USERS WHERE LOWER(EMAIL) = LOWER(:email)
            return await _context.Users
                .FirstOrDefaultAsync(u => u.Email.ToLower() == email.ToLower());
        }

        // ── GET ALL ──────────────────────────────────────────────────────
        public async Task<IEnumerable<User>> GetAllAsync()
        {
            // EF Core SQL: SELECT * FROM USERS ORDER BY CREATED_AT DESC
            return await _context.Users
                .OrderByDescending(u => u.CreatedAt)
                .ToListAsync();
        }

        // ── EMAIL EXISTS ─────────────────────────────────────────────────
        public async Task<bool> EmailExistsAsync(string email)
        {
            // More efficient than GetByEmail — only checks existence, no data returned
            // EF Core SQL: SELECT COUNT(1) FROM USERS WHERE LOWER(EMAIL) = :email
            return await _context.Users
                .AnyAsync(u => u.Email.ToLower() == email.ToLower());
        }

        // ── ADD (INSERT) ─────────────────────────────────────────────────
        public async Task<User> AddAsync(User user)
        {
            // EF Core SQL: INSERT INTO USERS (...) VALUES (...)
            // After SaveChanges, user.Id is automatically set by Oracle
            await _context.Users.AddAsync(user);
            await _context.SaveChangesAsync();

            // Return the user with the new ID assigned by Oracle
            return user;
        }

        // ── UPDATE ───────────────────────────────────────────────────────
        public async Task<User> UpdateAsync(User user)
        {
            // Always update the timestamp
            user.UpdatedAt = DateTime.UtcNow;

            // EF Core SQL: UPDATE USERS SET ... WHERE ID = :id
            _context.Users.Update(user);
            await _context.SaveChangesAsync();

            return user;
        }

        // ── DELETE ───────────────────────────────────────────────────────
        public async Task DeleteAsync(int id)
        {
            var user = await GetByIdAsync(id);

            if (user == null)
                throw new NotFoundException("User", id);

            // EF Core SQL: DELETE FROM USERS WHERE ID = :id
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
        }
    }
}